### ISSUE TITLE
Add response to error array

### ISSUE THREAD

**Issue by mtdowling** [guzzle/aws-guzzle-handler#1]

**Comment by jeremeamia** [comment]
Is it not being added already? https://github.com/guzzle/aws-guzzle-handler/blob/master/src/GuzzleHandler.php#L128-L129

**Comment by mtdowling** [comment]
No, that only attempts to add it when there is a connection exception (which actually, there will never be a response for such an exception). We need to add the response when it's a RequestException.

**Comment by jeremeamia** [comment]
Got it. I'll fix that.

**Comment by jeremeamia** [comment]
ConnectException extends RequestException

**Comment by mtdowling** [comment]
Yeah, but it's a specific subclass of RequestException that almost never has a response. We need a check for RequestException to add the response, then a separate check for ConnectException to see if that flag needs to be set.

**Comment by jeremeamia** [comment]
A'ight!

**Comment by jeremeamia** [comment]
Fixed in 124fe5c3
